sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
install: yarn
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  only:
    - master
